spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://surferton.czkei64227l8.ap-northeast-2.rds.amazonaws.com:5432/surferton
    username: surferton
    password: surferton
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true